#!/bin/bash

echo "🚀 FastTrack - GitHub Repository Setup"
echo "======================================"
echo ""
echo "Your code is committed locally and ready to push!"
echo ""
echo "📊 Repository Stats:"
git log --oneline | wc -l | xargs echo "   Commits:"
git ls-files | wc -l | xargs echo "   Files:"
du -sh . | awk '{print "   Size: " $1}'
echo ""
echo "📝 Next Steps:"
echo ""
echo "1. Create a private GitHub repository:"
echo "   • Go to: https://github.com/new"
echo "   • Repository name: fasttrack (or any name you prefer)"
echo "   • Description: Speed tracking iOS app with Go backend"
echo "   • Select: Private ✓"
echo "   • Don't initialize with README (we already have one)"
echo "   • Click 'Create repository'"
echo ""
echo "2. Push your code:"
echo ""
echo "   Run these commands:"
echo "   ----------------"
echo "   cd $(pwd)"
echo "   git remote add origin https://github.com/YOUR_USERNAME/fasttrack.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "3. On your server, clone the repo:"
echo ""
echo "   git clone https://github.com/YOUR_USERNAME/fasttrack.git"
echo "   cd fasttrack/backend"
echo "   go build -o triprank-api"
echo ""
echo "   Then deploy to Kubernetes (see backend/DEPLOYMENT.md)"
echo ""
echo "🔐 Security Notes:"
echo "   • The repo is private - only you can access it"
echo "   • JWT secrets are not committed (.gitignore)"
echo "   • K8s secrets are templates only"
echo "   • Remember to set JWT_SECRET env var on server"
echo ""
echo "📦 What's Included:"
echo "   • Go backend with authentication"
echo "   • iOS SwiftUI app"
echo "   • Kubernetes manifests"
echo "   • Complete documentation"
echo ""
