apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fasttrack-staging

resources:
  - ../../base
  - namespace.yaml

patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml

labels:
  - pairs:
      environment: staging
    includeSelectors: true
    includeTemplates: true
