apiVersion: v1
kind: PersistentVolume
metadata:
  name: fasttrack-uploads-pv-staging
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: fasttrack-staging
    name: fasttrack-uploads-pvc
  hostPath:
    path: /data/fasttrack-uploads/staging
    type: DirectoryOrCreate
