apiVersion: v1
kind: PersistentVolume
metadata:
  name: fasttrack-uploads-pv-production
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: fasttrack-production
    name: fasttrack-uploads-pvc
  hostPath:
    path: /data/fasttrack-uploads/production
    type: DirectoryOrCreate
