apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fasttrack-api
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/proxy-body-size: "12m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - fast.toper.dev  # patched per overlay
      secretName: fasttrack-api-tls
  rules:
    - host: fast.toper.dev  # patched per overlay
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fasttrack-api
                port:
                  number: 80
