apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fasttrack-uploads-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""   # blank = use manually-bound PV via volumeName in overlay patch
